---
- hosts: localhost
  become: yes
  vars:
    - username: john
    - home_dir: /better-place/john
    - uid: 1234
    - shell_script: nice-script.sh

  tasks:
    - name: Ensure /better-place exists
      file:
        path: /better-place
        state: directory

    - name: Ensure user exists with specific UID and home directory
      user:
        name: "{{ username }}"
        home: "{{ home_dir }}"
        uid: "{{ uid }}"
        shell: /bin/bash
        create_home: yes
        skeleton: /etc/skel

    - name: Ensure sudo is installed
      apt:
        name: sudo
        state: present

    - name: Allow 'john' to run 'whoami' with sudo without a password
      blockinfile:
        path: /etc/sudoers.d/john
        create: yes
        block: |
          john ALL=(ALL) NOPASSWD: /usr/bin/whoami
      become: yes

    - name: Install necessary packages
      apt:
        name:
          - tmux
          - vim
        state: present

    - name: Download Terraform CLI
      get_url:
        url: https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: Unzip the Terraform CLI
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin
        remote_src: yes

    - name: Create skeleton directory for shell script
      file:
        path: /etc/skel
        state: directory

    - name: Create script in skeleton directory
      copy:
        content: |
          #!/bin/bash
          df -h
        dest: /etc/skel/{{ shell_script }}
        mode: '0755'
...

